### ISSUE TITLE
move executable into separate module

### ISSUE THREAD

**Issue by derhuerst** [mapbox/geojson-flatten#5]
The core of `geojson-flatten` is nice and clean, with only `1.4k` of code. The `geojson-flatten` executable makes that `2.3m` however.

I propose to move `geojson-flatten` into a module `geojson-flatten-cli`, as [it](https://github.com/search?q=user%3Asindresorhus+cli) [is](https://github.com/search?q=user%3Akevva+cli) [common ](https://github.com/search?q=user%3Ajonschlinkert+cli) in the JS ecosystem.

**Comment by tmcw** [comment]
I'd prefer to keep them in the same project. Once you have hundreds of projects to maintain, it's convenient to avoid newrepoing for noncritical reasons.

@derhuerst would you be interested in helping slim the dependencies of the CLI down, if download size is very important to you? Removing minimist would be a one or two line change, removing concat-stream is also very possible and simple.

**Comment by tmcw** [comment]
> Sure, I can understand. Are you aware that there are tools like greenkeeper that will help you with maintenance?

Yep, I use greenkeeper on other projects. It's great, but it automates maybe 10% of maintenance time.

> It's not only about me. Often, npm dependency trees are several levels deep. You end up pulling hundreds of dependencies, sometimes just remotely related to what you want to do, and if those don't optimize for file/bundle size, it get's crazy pretty quickly.

Sure; that's the benefit and problem with npm, and it doesn't have a clear solution imho, and it isn't an actual manifested problem in most cases. If hard drives fit 10mb of data, then this 2.3mb bloat would be pretty dire. But usually it's a minor annoyance.

> Many people will use this module as a library and therefor never touch sharkdown at all.

I don't think this is a good assumption to make off-the-bat, whether a module is used mainly as a CLI or as a library.

Happy to accept a PR slimming down the deps!
